name: Retract Release
on:
  issue_comment:
    types: [created]
jobs:
  retract:
    runs-on: ubuntu-latest
    name: Retract a release
    # not a pull request and has `#contains` on a line by itself
    # fromJSON is used to process escape sequences
    if: |
      !github.event.issue.pull_request &&
      contains(
        format(fromJSON('"\n{0}\n"'), github.event.comment.body),
        fromJSON('"\n#retract\n"')
      )
    steps:
      - name: Get repo contents
        uses: actions/checkout@v3
        with:
          path: .__publish__

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: yarn
          cache-dependency-path: .__publish__/yarn.lock

      - name: Install yarn dependencies
        run: yarn install --cwd ".__publish__"

      - name: Parse and set inputs
        id: inputs
        run: node .__publish__/src/publish/inputs.js

      - name: Comment and close
        if: ${{ fromJSON(steps.inputs.outputs.result).requester == github.event.sender.login }}
        env:
          PUBLISH_ARGS: ${{ steps.inputs.outputs.result }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node .__publish__/src/publish/retract.js
