name: Test
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

defaults:
  run:
    shell: bash
jobs:
  unit-test:
    runs-on: ubuntu-latest
    name: unit tests
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38
        with:
          node-version: 24
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package.json', 'yarn.lock') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test
